Output (n_samples, n_dim) for predict_proba
strongio/foundry pull request #11
Opened 2022-10-31 19:30 UTC by jwdink

2022-11-07 17:27 UTC, andywong36 requested changes
Some comments below

Adding `('negative_binomial', True)` to L43 of `test_glm.py` means it still works. Which is bizarre - how would a distribution with support over ${0, 1, ..., \infty}$ work?

So I decided to try it, and we have the following:
```
from sklearn.datasets import make_classification
from foundry.glm import Glm
X, y = make_classification(n_informative = 6, n_classes = 4)  # X.shape is (100, 20), y.shape is (100, )
model = Glm("negative_binomial").fit(X, y)
model.predict(X)  # This is (100, 1). Should this have been (100, )? @jwdink in meeting: we should just follow the convention on skl
model.predict_proba(X)  # This is (100, 2). That doesn't make sense to me. 
```

2022-11-28 15:21 UTC, jwdink commented
@andywong36 OK, this was tricky, but I have a 2nd stab at this, take a look at the updated description above, and the updated PR.

2022-11-28 15:23 UTC, jwdink commented
Now that we have `is_classifier`, I no longer have an excuse not to support R^2 scoring for non-classifiers 😬

2023-01-04 16:55 UTC, andywong36 commented
@jwdink I'd like to hold off on this review until I complete #16 so I can better understand what's going on.

2023-01-04 20:40 UTC, andywong36 requested changes

2023-01-04 20:40 UTC, andywong36 commented on foundry/glm/glm.py
> +                ydict['value'] = to_tensor(ydict['value'], dtype='int', device=_to_kwargs['device'])
```suggestion
                ydict['value'] = to_tensor(ydict['value'], dtype=torch.long, device=_to_kwargs['device'])
```

I was getting an error. Unsure what this does, this modification seemed to let the code run.

2023-01-19 19:57 UTC, merged